services:
  - type: web
    name: praesidiumx-api
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        value: changeme123
        